
server:
  port: 4448
  contextPath: /servermain

serverauth:
  url: https://localhost:1111

servermail:
  auth: true
  starttlsenable: true
  starttlsrequired: true
  sslenable: true
  testconnection: true
  encoding: UTF-8

spring:
  profiles: dev
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true

multitenancy:
  servermain:
    dataSources:
      -
        conId: 0
        url: jdbc:postgresql://localhost:5432/servermain
        username: postgres
        password: ENC(e6TY2nTHNJhLB8dQ17qNQKmyId2qz8on)
        driverClassName: org.postgresql.Driver
