debug: true
 
spring:
  profiles:
    active:
    - dev
  http:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

jasypt:
    encryptor:
        bean: encryptorBean
        password: ${JASYPT_ENCRYPTOR_PASSWORD:}
        